### ISSUE TITLE
Question: Where should images be stored?

### ISSUE THREAD

**Issue by adswa** [psychoinformatics-de/rdm-course#1]
There are a number of useful visualizations for DataLad concepts, e.g., https://github.com/datalad-handbook/artwork/blob/master/src/publishing/publishing_network_gitvsannex.svg. Can I store them in the ``fig`` directory, or do you want them to go somewhere else, or ordered according to lessons in some way?

**Comment by mslw** [comment]
Personally, I don't have a preference. It looks like files can be referenced as `{{ page.root }}/some/path` so `fig` seems to be a good place, and the inner layout is secondary. NB, external links can also be used, but I agree it might be good to keep our content self-contained.

With the list of sources you provided in #2, another question is whether we should throw them all in, or add them as needed when building the materials. Right now, the `fig` directory still has some holdovers from the Carpentry shell lesson.
