### ISSUE TITLE
Remote collaboration module contents

### ISSUE THREAD

**Issue by mslw** [psychoinformatics-de/rdm-course#11]
This day 2 module (3rd or 4th module in general) should introduce the following `datalad` commands: `clone`, `get`, `drop`, `push`, `update`.

My first idea for the narrative:
- publish the example dataset created in module 1 (including walk-through of GIN UI)
- clone it into another folder and make changes
- push changes to gin 
- update in original location

Potential problems with this idea, raised in #4 and #8 
- publishing from binder would be incomplete (no annexed contents)
- in binder, the example from day 1 would be gone (but maybe we can make a script which generates a dataset which is identical to the one created during walk-through)

Open questions:
Maybe the order should be changed, and clone introduced before push?

**Comment by adswa** [comment]
>     * in binder, the example from day 1 would be gone (but maybe we can make a script which generates a dataset which is identical to the one created during walk-through)

Maybe you could conclude the first day by publishing the contents to somewhere where they can be retrieved. You can do it explicitly as a "please follow these steps and copy paste, we'll discuss the details of this tomorrow"-thing. This way, they have used command not formally introduced yet already, but this could be beneficial in getting a better understanding of everything in the end. 
That being said, it would probably be a good idea to have a script or published dataset that can be used to get to the desired state to be prepared for people who came late or dropped out earlier out of a previous module

**Comment by jsheunis** [comment]
+1 to both of @adswa's comments.

To enhance the collaborative aspect the participants could consider working in pairs, cloning and updating each other's datasets. The downside is that this might add some complications like not having push access to the other's repo, and having to explain branches/PRs (assuming that wasn't covered in detail previously).

**Comment by mslw** [comment]
Thanks for the comments! I think these are good ideas, but I see potential problems.

If putting publishing in the first module, `datalad siblings add` & `datalad push` won't take much time, but with GIN that relies on a) having an account b) manually creating a repo c) maybe setting up an ssh key. If we did it all on day 2 we could walk through b) and c) and only ask participants to do a). This would take time off workshop, but reduce frontloading.

I fully agree with having a script or a published dataset. I like the idea that a script could run up to one of a few desired states, not just until the end.

Working in pairs sounds ideal, but I can't judge whether that's manageable / feasible with time constraints and a remote setting?  I would avoid explaining branches and PRs in the introductory module and maybe altogether. My first thought was that after pushing to a remote the participants could clone their dataset into another location and work with that. But maybe, if we limit ourselves to one or two operations, doing that in pairs could be very satisfying? If we come up with a scenario, we could test it between ourselves.

**Comment by mslw** [comment]
With first draft in, I think we can close this one.
