### ISSUE TITLE
Additional materials (carried over)

### ISSUE THREAD

**Issue by mslw** [psychoinformatics-de/rdm-course#3]
I have noticed that in addition to the Lessons/Episodes (displayed on the title page, see https://psychoinformatics-de.github.io/rdm-course/, there is a lot of other materials, accessible from the menu bar at the top, carried over from the Software Carpentry Shell lesson:

- Code of Conduct
- Setup (i.e. instructions for participants)
- Extras (incl. Reference and Instructor Notes)
- License

I think it's good to have these things in our materials, but the content would need to be overhauled or replaced altogether. My question is how to best proceed with it:

- excise all content now and gradually repopulate
- keep all content as guidance and gradually morph it
- use this as a chance to start over with a cleaner template, transfer stylistic changes (not sure if productive at all, but I'm just floating it)

Similar applies to the pictures folder is also populated with bash-specific illustrations. Thoughts or preferences?

**Comment by adswa** [comment]
I'd vote for 2, "keep all content as guidance and gradually morph it".
This way, we can go through existing contents, update them where they need an update, extend them where necessary, and keep what is useful with appropriate credit.
Removing them first may make us miss cool information/structure they had used, and I think we can learn a lot from how they are structuring their workshops :) 

But I'm also in favor of starting this migration as soon as possible - at least those bits and pieces that can be done right away and don't rely on further meetings.

**Comment by mslw** [comment]
I agree, this approach sounds reasonable. The first two items from the menu (code of conduct & setup) seem to be the easiest to act upon. I will get to them in the next couple of days, together with writing down the first lesson(s).

The code of conduct could replace the Software Carpentry one with the (extremely concise, but thus equally applicable to material preparation and workshop participation) [one from datalad](https://github.com/datalad/datalad/blob/master/CODE_OF_CONDUCT.md) itself.

For setup, I was thinking about picking fragments [from the handbook](http://handbook.datalad.org/en/latest/intro/installation.html#install) and also adding the information about binder as an alternative.

I could do this as a starting point. When I'm done, I'll appreciate if you could take a look (unless you want to take over some of the installation part for example).

Then we can have a separate discussion on what else should be included; whether we want people to install some python packages (eg. with pillow we could build data processing examples around basic manipulations of png files) or suggest registering on GitHub / GIN / sth else for the publishing part (could be too much frontloading, I know).

**Comment by adswa** [comment]
> The code of conduct could replace the Software Carpentry one with the (extremely concise, but thus equally applicable to material preparation and workshop participation) one from datalad itself.

I personally think that the datalad code of conduct isn't really that good :D Maybe we can at least adopt a standard one, like https://github.com/datalad-handbook/book/blob/master/CODE_OF_CONDUCT.md

**Comment by mslw** [comment]
Thanks! This sounds like a better idea and I 100 % agree. I'll give it (and its source material) a thorough read.

**Comment by mslw** [comment]
This has been tidied up over time by the linked commits and some more, so I am closing this issue and opening a new one, specifically related to Reference (in extras).
