### ISSUE TITLE
Should we use external storage for publishing? If so, which one?

### ISSUE THREAD

**Issue by mslw** [psychoinformatics-de/rdm-course#4]
In the module on remote cooperation, we are planning to cover datalad clone, get/drop, push, and update. I think we could feature some remote hosting service and have all (interested) participants upload & download their dataset during this workshop module. Is it a good idea, or should we do local siblings only?

If yes, which external storage should we use during the workshop? Obviously, it should be free and easy to use. The possibilities are:
- Gin (good to showcase, especially for German neuroscientists)
- GitHub (to show what it means to publish dataset and not its content)
- Dropbox (most people probably have accounts, but I don't like it)
- Other?

Gin has the downside (or upside, depending how to look at it) that it blurs the boundary between git and git-annex. FWIW, the [Yale Repronim Workshop from the Handbook](https://handbook.datalad.org/en/latest/code_from_chapters/yale.html) did feature Gin. 

Thoughts?

**Comment by adswa** [comment]
> Other?

We could also do OSF (requires ``datalad-osf``).

I personally like Gin (gives them real-world experience on how to publish data) and GitHub (maybe in combination; or with an example that shows a recomputation when data can't be retrieved). The one thing to keep in mind in preparations that Gin needs an SSH key setup from all participants to push data, IIRC

**Comment by mslw** [comment]
> The one thing to keep in mind in preparations that Gin needs an SSH key setup from all participants to push data, IIRC

Ah, bummer. I checked and indeed, annexed content is not pushed with https:
```
datalad siblings
.: here(+) [git]
.: gin-https(-) [https://gin.g-node.org/msz/rdm-workshop-alt.git (git)]
.: gin(+) [git@gin.g-node.org:/msz/rdm-workshop-warmup.git (git)]
```

Setting up the ssh key wouldn't be too bad even during the workshop. The problem is that, according to our previous discussions and my googling, mybinder.org blocks outgoing ssh connections. So this would be a deal-breaker for people doing the exercises on binder (not a complete deal-breaker as they could still publish their dataset without annex and use some other dataset for cloning, but that would take some explaining).

**Comment by mslw** [comment]
So far, I have favoured GIN assuming that we may end up having access to a platform with SSH (e.g. the littlest jupyter hub) and wrote based on that,

For the first installment, featuring a hosting with WebDAV remains an alternative (may seem more familiar, doesn't require ssh). @mih wants to have the prototype of "push to anywhere" before the workshop and suggested for consideration whether we would like to feature it prominently during the workshop. While it should be very useful to present it to the SFB, I have some reservations about doing so during the workshop: by staying with GIN we could aim for a collaborative `push - clone - update` kind of workflow, see #11. Also, for institutional hosting, we'd need to make sure participants are able to get their accounts.

I'm leaving this issue open for now.

**Comment by mslw** [comment]
For the record: we are going with GIN, for these reasons:

- DataLad integrates nicely with GIN, so during the workshop we can push the entire dataset into one place.
- GIN has its quirks, but so do other services.
- The motions (creating a repository, setting up SSH keys, copying addresses etc.) are the same as for other git-based solutions. Although setting SSH access in particular can be seen as a time-consuming side-note, I think it's worth doing it during the workshop - these things often cause newcomer confusion in my experience.
