### ISSUE TITLE
Add section "For instructors" to the course site

### ISSUE THREAD

**Issue by jsheunis** [psychoinformatics-de/rdm-course#40]
Suggested content:
- describe how to set up [The Littllest Jupyter Hub](https://tljh.jupyter.org/en/latest/index.html) on AWS (mostly with info from [this issue](https://github.com/psychoinformatics-de/rdm-course/issues/19))
- describe user management
- point to slides to use
- other handy suggestions when running a course workshop

**Comment by adswa** [comment]
This was done in  #41 and the issue can be closed :)
