### ISSUE TITLE
Require python & pillow to make examples more interesting?

### ISSUE THREAD

**Issue by mslw** [psychoinformatics-de/rdm-course#5]
I would like to include some "meaningful" data manipulation with code when showcasing `datalad run`.

Inspired by previous datalad tutorials, I came up with an idea of using jpeg files to represent binary data stored in the dataset. In this case, "image processing" could be demonstrated by converting an image to greyscale. This could be done with python + pillow. An example script, representing custom code placed in the dataset (participants would just download or copy-paste it) would only have a few lines and the image manipulation would be easy to see.

For people working in binder this would not be a problem, as we can include pillow in the environment (as a side note - jupyter lab has a viewer for image files, so they could be seen). What about people working from their own laptops - would it be too much frontloading to add python & pillow to requirements? Pillow itself is lightweight and IMHO people willing to install datalad on their own machine would not have a problem with creating a virtualenv. However, I'm happy to discuss.

**Comment by adswa** [comment]
sounds good to me!

**Comment by mslw** [comment]
When we talked today, @mih raised two concerns about this idea:
- "image processing" might not be a sufficiently domain-agnostic example (tsv files are probably the most universal type of data)
- it's good to avoid too much versatility in the technology early on

These are good points but I'm still inclined to roll with this idea, because:
- we would do text manipulation by hand anyway, in readmes and some (simple) sidecar metadata
- it's easy to see that a new image has been created and it open it to confirm that it was desaturated, which clearly communicates that data manipulation happened (arguably more so than adding a line to tsv - personally I think pictures can be less boring)
-  this can work just as well on a laptop and in binder (jupyter lab interface has a file browser in the side panel and a built-in image viewer)
- when using `text2git` configuration, images nicely represent binary data in contrast to text files
- although images might not be representative of everyone's data, jpegs should still be a familiar territory for everyone
- crucially, I think that this is simple enough to serve as an example of "data manipulation with a script, requiring input and output", where python represents "a scripting language of one's choice", and the code is provided to represent "custom script" without dwelling on the specifics (but I've been using python for a long time, so feel free to challenge me on the assumption that it can serve as a natural example)

**Comment by mslw** [comment]
Looks like we're fine with it.
