### ISSUE TITLE
What is a good file name?

### ISSUE THREAD

**Issue by mslw** [psychoinformatics-de/rdm-course#6]
We have unanimously agreed that "what makes a good filename" is an important topic for the module on "structured data". In the first draft ([rendered](https://psychoinformatics-de.github.io/rdm-course/02-structuring-data/index.html) / [raw](https://github.com/psychoinformatics-de/rdm-course/blob/gh-pages/_episodes/02-structuring-data.md)) I closely followed the [Naming Things](http://www2.stat.duke.edu/~rcs46/lectures_2015/01-markdown-git/slides/naming-slides/naming-slides.pdf) presentation by Jenny Bryan. That presentation proposes the following pattern as a model example: `2013-06-26_BRAFWTNEGASSAY_Plasmid-Cellline-100-1MutantFraction_A01.csv` and uses it to discuss ordering, ISO dates, ability to split by underscores etc.

Question is whether we really want to use this example. The key message here is that the filename should contain essential information in a structured manner. It's worthwile to say that in cases where the date is part of the essential information (IDK, weather data collected daily), using ISO 8601 is a really good idea. But one could argue that this is rarely the case, especially when version control is in place, and using this example could make an incorrect impression that date at the beginning is always the way to go (while in some contexts it would be hardly different from _v1 _v2 _v3).

For example, there is [this presentation](https://slides.djnavarro.net/project-structure/) from Danielle Navarro which mimics the "Naming Things" presentation but uses different examples and, indeed, relegates dates to further in the discussion.

As a side note, several other naming tutorials which I saw all seem to revolve around similar ideas and mostly differ with regard to some details (eg. some suggest that hyphens should be avoided because they let en- or em-dashes creep up on you; I admit I had that happen but don't think it's a major obstacle). In any case I think we should note that we don't present the one and only truly gold standard way of naming things, and these are just examples of good practice to be applied when no domain-specific standard is in place.

Thoughts on what *is* a good filename and which examples to use are welcome.

**Comment by adswa** [comment]
This is a tough question, I have to admit it is much easier to determine what is not a good habit in naming things :smile:. 
I personally agree to your notion that the filename with an ISO date is somewhat suboptimal. I personally don't find it very readable, I agree to your statement that it is superfluous with version control in place, and even when there are usecases where it may make sense, I don't see it apply in general.

I would probably start with a list of general "DON'TS" (e.g., spaces, why camelcasing can be annoying, ...), then with a lists of things to keep in mind for our target audience (e.g., no unanonymized information left in the filename? maybe redundant metadata?) and then maybe show examples that make good file names in specific fields, such as valid BIDS directories. But thats just a quick brainstorming, maybe others have more or different opinions.

**Comment by mslw** [comment]
With no further input, I think we have that covered. If anything comes up later on it can be added.
