### ISSUE TITLE
Too much examples of text file syntax in "structuring data"?

### ISSUE THREAD

**Issue by mslw** [psychoinformatics-de/rdm-course#7]
In the structuring data module ([rendered](https://psychoinformatics-de.github.io/rdm-course/02-structuring-data/index.html) / [raw](https://github.com/psychoinformatics-de/rdm-course/blob/gh-pages/_episodes/02-structuring-data.md)) I want to advertise lightweight text files for free-form descriptions (markdown), config files and data serialisation. In the initial draft, I couldn't decide on a single example for config/serialisation, so I included short examples of toml, yaml and json syntax (to show that syntax may differ, but the rules are usually simple). Perhaps it can be a bit overloading (config files and serialisation in itself may be novel to participants) and it's best to show just one of the three (which?) and focus on qualifying when these files may be needed.

**Comment by adswa** [comment]
Maybe as an alternative to leaving one out: does the template allow toggle-able elements, such that e.g., two can be hidden by default and expanded by clicking on it, if a reader desires?

**Comment by jsheunis** [comment]
Looks like the tabs have now/already been implemented, which looks good to me. I don't think this is overloading. If we feel like we need to add more info on "qualifying when these files may be needed", perhaps a short descriptive example of a config file (for some package or pipeline) could be useful. But I don't think this is critical.

**Comment by mslw** [comment]
Examples were kept in tabs, I think that it'll work nicely. Also added some motivation, and I think the current version does a decent job in suggesting when such files are needed.
