### ISSUE TITLE
Is Binder the primary or backup environment?

### ISSUE THREAD

**Issue by mslw** [psychoinformatics-de/rdm-course#8]
This is mostly a record of previous discussions, but eventually the decision about using mybinder will influence some choices regarding teaching.

Probably the decision will also depend on the target audience and we can ask them about it; if most of them would prefer to use binder then the live coding should also be done from binder (rather than in a plain terminal).

(my)binder downsides:
1. Does not allow outgoing ssh connections which hampers publishing annexed contents, as pointed out in #4 
2. Is not persistent: a dataset created by a participant on day 1 would not be there on day 2

binder upsides:
1. Guarantees everyone has the same environment
2. All in one (browser) window: provides terminal, editor, file browser, image viewer

Side note: a hosted jupyterhub instance with user accounts for all participants would probably be ideal from the user perspective. During initial discussions we were sceptical about hosting it on our infrastructure. But maybe spooling up something like the littlest jupyterhub on AWS is not out of question? Configuration (incl. users) is some overhead but doesn't seem scary, and costs seem to be in single dollars per hour for beefy instances. That would be for a live workshop only, and mybinder would be kept for everyone who wants to check things out on their own.

**Comment by jsheunis** [comment]
The jupyterhub that you configured on AWS seemed to work nicely. Did you find any particular downsides? I guess the biggest challenge would be administrative (even if costs are low)?

**Comment by mslw** [comment]
It ticked two important boxes: I was able to create an ssh key and use it to push/pull to and from gin, and the storage can be independent from the life of the compute instance (so you can shut it down and start it again with persistent data).

The instance we tried was running on a T3 small instance (2 GB RAM, 2 vCPUs, about 2 cents per hour) which is enough for 2-3 people at the same time, but for a proper workshop we'd need something in a dollar range (I'm guessing), like M5A Quadruple Extra Large (64 GB, 16 vCPUs, 69 cents per hour) or bigger (32 cores for 1.38 per hour). Prices per [here](https://instances.vantage.sh/). This doesn't include storage or transfer, but even without it seems to me that the cost should be reasonable for two half-days. Getting it refunded though could be a problem - don't think we have a precedent or procedure for that.

**Comment by mslw** [comment]
Thanks for getting the ball rolling with Binder @jsheunis - I've decided to take it a step further and use AWS in the first installment. I placed setup comments in a separate issue. Let's see how it works in practice.
